use_frameworks!

platform :ios, '8.0'

target 'LWAppMethodTimeConsuming_Example' do
  pod 'LWAppMethodTimeConsuming', :path => '../'

  target 'LWAppMethodTimeConsuming_Tests' do
    inherit! :search_paths

    
  end
end
